#Savellona, Sidney V. 's code

echo -n "ENTER YOUR NAME: "
read NAME

echo -n "ENTER YOUR AGE: "
read AGE

echo -n "ENTER YOUR FAVORITE PROGRAMMING LANGUAGE: "
read PLANGUAGE

echo "THANK YOU $NAME, YOU ARE $AGE YEARS OLD & YOUR FAVORITE PROGRAMMING LANGUAGE IS $PLANGUAGE"
